### ISSUE TITLE
Please publish latest version to npm

### ISSUE THREAD

**Issue by judah-firewood** [ijse/grunt-freemarker#13]
npm package shows the following in freemarker.js (line 35):
`resultData += iconv.decode(data, 'gbk');`
while github shows:
`resultData += iconv.decode(data, settings.encoding);`

Please publish latest to npm to allow for encoding options.

**Comment by ijse** [comment]
grunt-freemarker is not depend on freemarker.js

Did you mean `gulp-freemarker`? I've already upgraded.

**Comment by ijse** [comment]
Done. Thanks for your remind.
